# Generated by Django 4.1 on 2023-06-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("name", models.CharField(max_length=10)),
                ("birthday", models.DateField()),
                ("createtime", models.DateTimeField(auto_now_add=True)),
                (
                    "phonenumber",
                    models.CharField(
                        max_length=20, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=20)),
                ("deltag", models.BooleanField(default=False)),
            ],
        ),
    ]
