# Generated by Django 4.1 on 2023-07-07 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_userinfo_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="createtime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
